### ISSUE TITLE
NFR: Ability to run from Raspberry Pi

### ISSUE THREAD

**Issue by paper-skyline** [gavinying/modsim#1]
I'd love to be able to run this on a raspberry pi (arm64) for demonstration purposes, but docker keeps throwing an error that this isn't possible: "docker: no matching manifest for linux/arm/v7"

Trying to add "platform: linux/armv7" nor "platform: linux/arm64" didn't work either as a shot in the dark.

**Comment by gavinying** [comment]
Hi, let me add armv7 support in the next version. Thanks for suggestion.

**Comment by gavinying** [comment]
solved in latest version
