### ISSUE TITLE
FeatureRequest: provide values for client by config file

### ISSUE THREAD

**Issue by bruce3x** [gavinying/modsim#6]
Can you provide a way to input a config file like [Modpoll](https://github.com/gavinying/modpoll?tab=readme-ov-file#prepare-modbus-configure-file) to easy debugging as a mock server ?

Thanks

**Comment by gavinying** [comment]
It is possible technically, but I don't see much value on it for now. 
So far, I feel directly manipulating the code or memory space is still a better way to go. 
But I may review this in the future when priority comes. Thanks any way for your suggestion.
